"""ocr extraction + invoice line matches

Revision ID: 3e7d82c89bb3
Revises: 81ca77890c1d
Create Date: 2026-08-13 18:50:39.928813
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3e7d82c89bb3'
down_revision: str | None = '81ca77890c1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_line_matches',
    sa.Column('match_history_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('raw_description', sa.String(length=512), nullable=False),
    sa.Column('raw_product_code', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.Column('matched_product_name', sa.String(length=255), nullable=True),
    sa.Column('matched_po_line_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'auto_matched', 'llm_matched', 'confirmed', 'corrected', 'unmatched', name='line_match_status'), server_default='pending', nullable=False),
    sa.Column('final_product_id', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_history_id'], ['match_history.id'], name=op.f('fk_invoice_line_matches_match_history_id_match_history'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_matches'))
    )
    op.create_index('ix_line_matches_history', 'invoice_line_matches', ['match_history_id'], unique=False)
    op.create_index('ix_line_matches_status', 'invoice_line_matches', ['status'], unique=False)
    op.add_column('match_history', sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('match_history', sa.Column('extracted_untaxed', sa.Float(), nullable=True))
    op.add_column('match_history', sa.Column('match_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_history', 'match_reasoning')
    op.drop_column('match_history', 'extracted_untaxed')
    op.drop_column('match_history', 'extracted_json')
    op.drop_index('ix_line_matches_status', table_name='invoice_line_matches')
    op.drop_index('ix_line_matches_history', table_name='invoice_line_matches')
    op.drop_table('invoice_line_matches')
    # ### end Alembic commands ###

    # Hand-added. Alembic emits CREATE TYPE implicitly as part of create_table
    # but never the matching DROP TYPE, so without this a downgrade leaves the
    # enum behind and the next upgrade fails with
    # 'type "line_match_status" already exists'.
    op.execute("DROP TYPE IF EXISTS line_match_status")
