"""invoice intake: match_history, notifications, batches

Revision ID: 81ca77890c1d
Revises: 3fed46c5c1c4
Create Date: 2026-08-13 16:01:10.307646
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '81ca77890c1d'
down_revision: str | None = '3fed46c5c1c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_batches',
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('created', 'processing', 'completed', 'partial_failure', 'failed', name='batch_status'), server_default='created', nullable=False),
    sa.Column('total_invoices', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_processing_batches_started_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_batches'))
    )
    op.create_index('ix_batches_started_by', 'processing_batches', ['started_by'], unique=False)
    op.create_index('ix_batches_status', 'processing_batches', ['status'], unique=False)
    op.create_table('match_history',
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('member_ref_no', sa.String(length=120), nullable=True),
    sa.Column('member_notes', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('ocr_model', sa.String(length=100), nullable=True),
    sa.Column('ocr_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('ocr_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('extracted_vendor', sa.String(length=255), nullable=True),
    sa.Column('extracted_invoice_no', sa.String(length=120), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_total', sa.Float(), nullable=True),
    sa.Column('extracted_currency', sa.String(length=10), nullable=True),
    sa.Column('extracted_tax', sa.Float(), nullable=True),
    sa.Column('extracted_line_count', sa.Integer(), nullable=True),
    sa.Column('matched_po_id', sa.Integer(), nullable=True),
    sa.Column('matched_po_name', sa.String(length=120), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_strategy', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'ocr_queued', 'ocr_processing', 'ocr_failed', 'ocr_done', 'matching', 'match_failed', 'pending_review', 'no_match', 'confirmed', 'corrected', 'rejected', 'pushed', name='invoice_status'), server_default='uploaded', nullable=False),
    sa.Column('was_corrected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('final_po_id', sa.Integer(), nullable=True),
    sa.Column('pushed_to_odoo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_bill_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['processing_batches.id'], name=op.f('fk_match_history_batch_id_processing_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_match_history_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_match_history_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_history'))
    )
    op.create_index('ix_match_history_batch', 'match_history', ['batch_id'], unique=False)
    op.create_index('ix_match_history_created', 'match_history', ['created_at'], unique=False)
    op.create_index('ix_match_history_status', 'match_history', ['status'], unique=False)
    op.create_index('ix_match_history_tenant', 'match_history', ['tenant_id'], unique=False)
    op.create_index('ix_match_history_tenant_status', 'match_history', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_match_history_uploader', 'match_history', ['uploaded_by'], unique=False)
    op.create_table('notifications',
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('invoice_uploaded', 'processing_started', 'ocr_completed', 'ocr_failed', 'match_found', 'no_match_found', 'invoice_confirmed', 'invoice_corrected', 'invoice_rejected', 'invoice_pushed', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('match_history_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['processing_batches.id'], name=op.f('fk_notifications_batch_id_processing_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_history_id'], ['match_history.id'], name=op.f('fk_notifications_match_history_id_match_history'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notif_match_history', 'notifications', ['match_history_id'], unique=False)
    op.create_index('ix_notif_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('users', sa.Column('odoo_partner_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('odoo_partner_name', sa.String(length=255), nullable=True))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_column('users', 'odoo_partner_name')
    op.drop_column('users', 'odoo_partner_id')
    op.drop_index('ix_notif_user_unread', table_name='notifications')
    op.drop_index('ix_notif_match_history', table_name='notifications')
    op.drop_index('ix_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_match_history_uploader', table_name='match_history')
    op.drop_index('ix_match_history_tenant_status', table_name='match_history')
    op.drop_index('ix_match_history_tenant', table_name='match_history')
    op.drop_index('ix_match_history_status', table_name='match_history')
    op.drop_index('ix_match_history_created', table_name='match_history')
    op.drop_index('ix_match_history_batch', table_name='match_history')
    op.drop_table('match_history')
    op.drop_index('ix_batches_status', table_name='processing_batches')
    op.drop_index('ix_batches_started_by', table_name='processing_batches')
    op.drop_table('processing_batches')

    # Hand-added. Alembic emits CREATE TYPE implicitly as part of create_table
    # but never emits the matching DROP TYPE, so without these lines a
    # downgrade leaves the enum types behind and the next upgrade fails with
    # 'type "invoice_status" already exists'.
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS invoice_status")
    op.execute("DROP TYPE IF EXISTS batch_status")
    # ### end Alembic commands ###
